version: '3'

services:
  mariadb:
    image: mariadb
    expose:
      - 3306
    environment:
      MARIADB_DATABASE: employees
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
      MARIADB_USER: employees
      MARIADB_PASSWORD: employees
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      interval: 5s
      retries: 3
      timeout: 30s

  employees-app:
    image: employees:1.0.0
    depends_on:
      - mariadb
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mariadb://mariadb:3306/employees'
      SPRING_DATASOURCE_USERNAME: employees
      SPRING_DATASOURCE_PASSWORD: employees
    expose:
      - 8080
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 5s
      retries: 3
      timeout: 30s

  employees-newman:
    build: .
    image: employees-newman
    volumes:
    - ./reports:/tests/reports
    depends_on:
      employees-app:
        condition: service_healthy
