version: '3'

services:
  employees-app:
      image: training360/employees:latest
      volumes:
        - gitlab-runner-builds:/builds
      entrypoint: ["${E2E_HOME}/wait/wait-for-it.sh", "-t", "120", "mariadb:3306", "--", "java", "org.springframework.boot.loader.JarLauncher"]

  employees-newman:
      volumes:
        - gitlab-runner-builds:/builds
      entrypoint: ["${E2E_HOME}/wait/wait-for-it.sh", "-t", "30", "employees-app:8080", "--", "newman", "run", "employees.postman_collection.json", "-e", "test.postman_environment.json", "-r", "cli,htmlextra", "--reporter-htmlextra-export", "${E2E_HOME}/reports"]

volumes:
  gitlab-runner-builds:
    external: true
    name: gitlab-runner-builds