version: '3'
services:
  jenkins:
    build: .
    image: jenkins-with-docker
    ports:
      - 8095:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-data:/var/jenkins_home

volumes:
  jenkins-data:
    name: jenkins-data